name: CI
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hell world"
      - name: Print goodbye
        run: echo "goodbye"
    
  
